---
- hosts: all
  sudo: yes
  vars:
    phantom: phantomjs-1.9.1-linux-x86_64

  tasks:
    - name: ensure destination stow exists
      file: path=/usr/local/stow state=directory owner=root group=root

    - name: get the package
      get_url:
        url: http://phantomjs.googlecode.com/files/{{phantom}}.tar.bz2
        dest: /tmp/{{phantom}}.tar.bz2
        force: no
        owner: root
        group: root

    - name: untar the package
      shell: tar -xjvf /tmp/{{phantom}}.tar.bz2 -C /usr/local/stow creates=/usr/local/stow/{{phantom}}

    - name: stow phantomjs
      shell: stow -R -d /usr/local/stow -t /usr/local {{phantom}}
